# https://tekton.dev/docs/pipelines/auth/
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: chanmi910
  password: 8804ff0c-896e-49c0-9cec-d6cbce7babb7
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
secrets:
  - name: docker-secret