apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/git-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi