apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  params:
    - name: whatyousay
      type: string
      description: ddd
      default: byebye
  tasks:
    - name: hello
      taskRef:
        name: hello
      params:
        - name: testparam
          value: "$(params.testparam)"